services:

  testrunner:
    image: $DEV_IMAGE_TAG
    build:
      dockerfile: Dockerfile.dev
      context: .
      args:
        OTP_VERSION: $OTP_VERSION
        THRIFT_VERSION: $THRIFT_VERSION
    volumes:
      - .:$PWD
    hostname: hellgate
    depends_on:
      db:
        condition: service_healthy
      dmt:
        condition: service_healthy
      party-management:
        condition: service_healthy
      limiter:
        condition: service_healthy
      shumway:
        condition: service_started
      bender:
        condition: service_healthy
      cubasty:
        condition: service_healthy
    working_dir: $PWD
    command: /sbin/init

  dmt:
    image: ghcr.io/valitydev/dominant-v2:sha-ab393d5
    command: /opt/dmt/bin/dmt foreground
    environment:
      DMT_KAFKA_ENABLED: "0"
    volumes:
      - ./test/dmt/sys.config:/opt/dmt/releases/0.1/sys.config
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/opt/dmt/bin/dmt", "ping"]
      interval: 5s
      timeout: 3s
      retries: 12

  bender:
    image: ghcr.io/valitydev/bender:sha-bc14c2e
    command: /opt/bender/bin/bender foreground
    volumes:
      - ./test/bender/sys.config:/opt/bender/releases/1.0.0/sys.config
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/opt/bender/bin/bender", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  limiter:
    image: paycore:local-dev
    build:
      context: .
      args:
        - OTP_VERSION
        - THRIFT_VERSION
    command: ["/opt/limiter/bin/limiter", "foreground"]
    depends_on:
      liminator:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/opt/limiter/bin/limiter", "ping"]
      interval: 5s
      timeout: 1s
      retries: 20

  shumway:
    image: ghcr.io/valitydev/shumway:sha-d198581
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    entrypoint:
      - java
      - -Xmx512m
      - -jar
      - /opt/shumway/shumway.jar
      - --spring.datasource.url=jdbc:postgresql://db:5432/shumway
      - --spring.datasource.username=shumway
      - --spring.datasource.password=postgres
      - --management.endpoint.metrics.enabled=false
      - --management.endpoint.prometheus.enabled=false
    healthcheck:
      disable: true

  liminator:
    image: ghcr.io/valitydev/liminator:sha-4f2cfbb
    restart: unless-stopped
    entrypoint:
      - java
      - -Xmx512m
      - -jar
      - /opt/liminator/liminator.jar
      - --spring.datasource.url=jdbc:postgresql://db:5432/liminator
      - --spring.datasource.username=liminator
      - --spring.datasource.password=postgres
      - --service.skipExistedHoldOps=false
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8022/actuator/health"]
      interval: 5s
      timeout: 1s
      retries: 20

  party-management:
    image: ghcr.io/valitydev/party-management:sha-e3fe0dc
    command: /opt/party-management/bin/party-management foreground
    volumes:
      - ./test/party-management/sys.config:/opt/party-management/releases/0.1/sys.config
    depends_on:
      db:
        condition: service_healthy
      dmt:
        condition: service_started
      shumway:
        condition: service_started
    healthcheck:
      test: ["CMD", "/opt/party-management/bin/party-management", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  cubasty:
    image: ghcr.io/valitydev/cubasty:sha-f94b6a0-epic-fix_matched
    volumes:
      - ./test/cubasty/sys.config:/opt/cs/releases/0.1/sys.config
    hostname: cubasty
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/opt/cs/bin/cs", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  db:
    image: postgres:17
    command: -c 'max_connections=1000'
    environment:
      POSTGRES_MULTIPLE_DATABASES: "hellgate,fistful,bender,dmt,party_management,shumway,liminator,customer_storage"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./test/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hellgate"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
